default_velocity_scaling_factor: 0.5
default_acceleration_scaling_factor: 0.5

joint_limits:
  base_link_to_link1:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 6.0
    has_effort_limits: true
    max_effort: 20.0

  link1_to_link2:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 6.0
    has_effort_limits: true
    max_effort: 15.0

  link2_to_link3:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 4.5
    has_effort_limits: true
    max_effort: 10.0

  link3_to_gripper_link:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 3.0
    has_effort_limits: true
    max_effort: 5.0
